//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products
    {
        public int idSale { get; set; }
        public Nullable<double> idArticle { get; set; }
        public Nullable<int> idPartner { get; set; }
        public Nullable<int> countProduct { get; set; }
        public Nullable<System.DateTime> dateOfSale { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
    }
}
