//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class MasterPolEntities1 : DbContext
    {
     
        private static MasterPolEntities1 _context;

        public static MasterPolEntities1 GetContext()
        {
            if (_context == null)
                _context = new MasterPolEntities1();

            return _context;
        }
    
        public MasterPolEntities1()
            : base("name=MasterPolEntities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Partner_products> Partner_products { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Partners_type> Partners_type { get; set; }
        public virtual DbSet<Product_type> Product_type { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}