USE [master]
GO

/****** Object:  Database [MasterPol]    Script Date: 09.04.2026 10:17:36 ******/
DROP DATABASE [MasterPol]
GO

/****** Object:  Database [MasterPol]    Script Date: 09.04.2026 10:17:36 ******/
CREATE DATABASE [MasterPol]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MasterPol', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MasterPol.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MasterPol_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MasterPol_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [MasterPol] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MasterPol].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MasterPol] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MasterPol] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MasterPol] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MasterPol] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MasterPol] SET ARITHABORT OFF 
GO

ALTER DATABASE [MasterPol] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MasterPol] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MasterPol] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MasterPol] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MasterPol] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MasterPol] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MasterPol] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MasterPol] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MasterPol] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MasterPol] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MasterPol] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MasterPol] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MasterPol] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MasterPol] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MasterPol] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MasterPol] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MasterPol] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MasterPol] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MasterPol] SET  MULTI_USER 
GO

ALTER DATABASE [MasterPol] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MasterPol] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MasterPol] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MasterPol] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MasterPol] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MasterPol] SET QUERY_STORE = OFF
GO

USE [MasterPol]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [MasterPol] SET  READ_WRITE 
GO


